name: VanillaOS kinetic

on:
  workflow_dispatch:
    branches: [ kinetic ]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: debian:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v2

    - name: Install debootstrap/git
      run: apt update && apt install git debootstrap -y

    - name: Build ISO
      run: |
        cd /
        git clone https://github.com/Vanilla-OS/iso-builder
        cd iso-builder
        ./build.sh etc/terraform.conf

    - uses: actions/upload-artifact@v2
      with:
        name: VanillaOS 22.10
        path: /iso-builder/builds/
